"use client";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '../providers/theme-provider';
import ConvexClientProvider from "../providers/convex-client-provider";
import './globals.css';
import { usePathname } from 'next/navigation';
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
            <ConvexClientProvider>
              {pathname !== "/sign-in" && (
                <SignedOut>
                  <SignInButton />
                </SignedOut>
              )}
              <SignedIn>
                <UserButton />
              </SignedIn>
              {children}
            </ConvexClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
