"use client";
import { Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '../providers/theme-provider';
import ConvexClientProvider from "../providers/convex-client-provider";
import './globals.css';
import { usePathname } from 'next/navigation';
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
})//this means that the fct accepts an object as arg,this object contains a children property .Then we have ts type annotation , React.ReactNode means anything that can be rendered in react like jsx basic variable types,fragments(<><>)...
{
  const pathname = usePathname();//allows you to access the current URL pathname within your components

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
            <ConvexClientProvider>

              <SignedIn>
                <UserButton />
              </SignedIn>
              {children}
              <Toaster />
            </ConvexClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
